# Generated by Django 4.1.5 on 2023-01-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_posts_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="title",
        ),
    ]
